### ISSUE TITLE
Add Solutions Chapter 1 & 2

### ISSUE THREAD

**Issue by julprat** [julprat/CourseDP_hub#4]
Solutions needed for Exercises:

1.1 and 2.3, 2.4, 2.5, 2.6, 2.8

I have included some hints on where to find the solutions.

Please check the solutions that I have added for the other exercises.

Add your inputs to the update branch and send me a pull request once ready.

**Comment by bmu099** [comment]
Files uploaded to a new branch "Sep19_Update".

**Comment by julprat** [comment]
In the proof of Exercise 2.3, I don't understand : we have $g\\left(x_{\\theta}\\right) = \\left(1-\\theta\\right)g\\left(x_{1}\\right) + \\theta g\\left(x_{2}\\right)$. I guess you mean $g\\left(x_{\\theta}\\right) \in \Gamma\\left(x_{\\theta}\\right)$?

Also, I believe that you forgot to mention the assumption that $f(.)$ is concave. Also, you might need to state the space of (weakly?) concave functions is closed.

Exercise 2.5, point 2: Showing that the counterexaample of point 1 does not work is not enough, no? You also need to prove that there is no counterexample. Here you can use the answer to 2.4, point 1.

**Comment by bmu099** [comment]
I have revised the answers to the questions mentioned above. Thank you!
